const ACTION = {
    INCOME: "INCOME",
    FOREIGN_AID: "FOREIGN_AID",
    TAX: "TAX",
    STEAL: "STEAL",
    ASSASSINATE: "ASSASSINATE",
    EXCHANGE: "EXCHANGE",
    COUP: "COUP",
}

const COUNTERACTION = {
    BLOCK_FOREIGN_AID: "BLOCK_FOREIGN_AID",
    BLOCK_STEAL: "BLOCK_STEAL",
    BLOCK_ASSASSINATION: "BLOCK_ASSASSINATION",
}

const ROYAL = {
    DUKE: "DUKE",
    CAPTAIN: "CAPTAIN",
    ASSASSIN: "ASSASSIN",
    CONTESSA: "CONTESSA",
    AMBASSADOR: "AMBASSADOR",
}

const ACTION_TO_ROYAL_MAP = {
    [ACTION.INCOME]: null,
    [ACTION.FOREIGN_AID]: null,
    [ACTION.TAX]: [ROYAL.DUKE],
    [ACTION.STEAL]: [ROYAL.CAPTAIN],
    [ACTION.ASSASSINATE]: [ROYAL.ASSASSIN],
    [ACTION.EXCHANGE]: [ROYAL.AMBASSADOR],
    [ACTION.COUP]: null,
}

const COUNTERACTION_TO_ROYAL_MAP = {
    [COUNTERACTION.BLOCK_FOREIGN_AID]: [ROYAL.DUKE],
    [COUNTERACTION.BLOCK_STEAL]: [ROYAL.CAPTAIN, ROYAL.AMBASSADOR],
    [COUNTERACTION.BLOCK_ASSASSINATION]: [ROYAL.CONTESSA],
}