export const ACTION = {
  INCOME: 'INCOME',
  FOREIGN_AID: 'FOREIGN_AID',
  TAX: 'TAX',
  STEAL: 'STEAL',
  ASSASSINATE: 'ASSASSINATE',
  EXCHANGE: 'EXCHANGE',
  COUP: 'COUP',
};

export const COUNTERACTION = {
  BLOCK_FOREIGN_AID: 'BLOCK_FOREIGN_AID',
  BLOCK_STEAL: 'BLOCK_STEAL',
  BLOCK_ASSASSINATION: 'BLOCK_ASSASSINATION',
};

export const ROYAL = {
  DUKE: 'DUKE',
  CAPTAIN: 'CAPTAIN',
  ASSASSIN: 'ASSASSIN',
  CONTESSA: 'CONTESSA',
  AMBASSADOR: 'AMBASSADOR',
};

export const ACTION_TO_ROYAL_MAP = {
  [ACTION.INCOME]: null,
  [ACTION.FOREIGN_AID]: null,
  [ACTION.TAX]: [ROYAL.DUKE],
  [ACTION.STEAL]: [ROYAL.CAPTAIN],
  [ACTION.ASSASSINATE]: [ROYAL.ASSASSIN],
  [ACTION.EXCHANGE]: [ROYAL.AMBASSADOR],
  [ACTION.COUP]: null,
};

export const COUNTERACTION_TO_ROYAL_MAP = {
  [COUNTERACTION.BLOCK_FOREIGN_AID]: [ROYAL.DUKE],
  [COUNTERACTION.BLOCK_STEAL]: [ROYAL.CAPTAIN, ROYAL.AMBASSADOR],
  [COUNTERACTION.BLOCK_ASSASSINATION]: [ROYAL.CONTESSA],
};
